/*
Copyright (c) 2026 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/

syntax = "proto3";

package custom.options;

import "google/protobuf/descriptor.proto";

// Custom field option for validation.
extend google.protobuf.FieldOptions {
  FieldConstraints constraints = 51234;
}

message FieldConstraints {
  int32 min_length = 1;
  int32 max_length = 2;
}
